## Education

-   PhD in Veterinary Medicine, University of Ghent, 2013:

    -   "[Health and Fertility Challenges in High Yielding Dairy Cows during the Transition Period and the Use of Dietary Fatty Acids as an Optimization Strategy](/files/pdfs/miel-hostens-cv.pdf)"

-   Master in Veterinary Medicine, University of Ghent, 2006 (*cum laude*).

-   Bachelor in Veterinary Medicine, University of Ghent,2003 (*cum laude*).

## Professional supplementary training and education

+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| ### Leadership domain                                                                                                                     |           |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| University Teaching Qualification at Centre for Academic Teaching and Learning, Utrecht, The Netherlands                                  | 2019      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Research Leadership Development Programme for talented researchers at Centre for Academic Teaching and Learning, Utrecht, The Netherlands | 2021      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| ### Dairy science domain                                                                                                                  |           |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Cursus rundveevoeding: recente ontwikkelingen en nieuwe inzichten, Wageningen Business School, The Netherlands                            | 2007      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| BASF, Tagungsveranstaltung, Haus Riswick, Germany                                                                                         | 2007      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| WIAS Seminar: Strategies to improve health and fertility in dairy cows, Wageningen, The Netherlands                                       | 2008      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| ITB Schulung Februar, DSP Agrosoft, Verden, Germany                                                                                       | 2008      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 14^th^ DISCOVER Conference: Lipids for Dairy Cattle: Today's Issues, Tomorrow's Challenges, Nashville, Indiana, United States             | 2008      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 25^th^ World Buiatrics Congress, Budapest, Hungary                                                                                        | 2008      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| International symposium: Nutritional strategies to manage the challenges of today's dairy cows, Wageningen, The Netherlands               | 2009      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| International Symposium on Ruminant Physiology, Clermont-Ferrand, France                                                                  | 2009      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Rindergesundheitstag -- Milch und gute Fruchtbarkeit: Die besten Strategien, Leipzig, Germany                                             | 2009      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| ITB Schulung August, DSP Agrosoft, Verden, Germany                                                                                        | 2009      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 17^th^ DISCOVER Conference: Dairy Herd Analytics, Nashville, United States                                                                | 2009      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 20^th^ Discover Conference: The Transition Cow: Biology and Management, Champaign, United States                                          | 2010      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Dairy Solutions Symposium -- Rumen Health : A 360° Analysis, Utrecht, The Netherlands                                                     | 2010      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Alta Value Services Konferenz, Bremen, Germany                                                                                            | 2010      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 14^th^ International Conference on Production Diseases in Farm Animals, Ghent, Belgium                                                    | 2010      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| International Reproduction Conference, Anchorage, United States                                                                           | 2010      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Bovine Professionals Meeting, Fertility and Rumen Health, Hofheim, Germany                                                                | 2010      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 21^st^ Discover Conference: Improving Reproductive Efficiency of Lactating Dairy Cattle, United States                                    | 2011      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 22^nd^ Discover Conference: Milk Components: Opportunities for Maximizing Farm Gate Returns, Chicago, United States                       | 2011      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Rindergesundheitstag, Giesen, Germany                                                                                                     | 2011      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| European Buiatrics Forum, Marseille, France                                                                                               | 2011      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Meeting American Association for Bovine Practitioners, Louisville, United States                                                          | 2011      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 25^th^ Discover Conference: New Developments in Immunity, Nutrition, and Management of the Preruminant Calf, Chicago, United States       | 2012      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 27^th^ World Buiatrics Congress, Lisbon, Portugal                                                                                         | 2012      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Meeting American Association for Bovine Practitioners, Toronto, Canada                                                                    | 2012      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 14^th^ international congress of sivar ,Cremona, Italy                                                                                    | 2012      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Bovine Professionals Meeting, Claw Health and Transition Management, Hofheim, Germany                                                     | 2012      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 26^th^ Discover Conference: Dairy Feed Efficiency, United States                                                                          | 2013      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Meeting of the European Society for Domestic Animal Reproduction, Milano, Italy                                                           | 2013      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Dairyland Initiative Meeting on Transition Cow and Positive Pressure Tube Ventilation, Madison, United States                             | 2013      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 28^th^ Discover Conference: Starch for Ruminants, Chicago, United States                                                                  | 2014      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Joint ASA-ADSA Annual Meeting, Kansas City, United States                                                                                 | 2014      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 65^th^ Annual Conference of the European Federation of Animal Science, Copenhagen, Denmark                                                | 2014      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Blanca Reproduction Workshop, Barcelona, Spain                                                                                            | 2015      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| ICAR Technical meeting, Cracow, Poland                                                                                                    | 2015      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 66^th^ Annual Conference of the European Federation of Animal Science, Warshau, Poland                                                    | 2015      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 7^th^ European Conference on Precision Livestock Farming, Milan, Italy                                                                    | 2015      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Large Dairy Herd Management Conference, Chicage, United States                                                                            | 2016      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 67^th^ Annual Conference of the European Federation of Animal Science, Belfast, United Kingdom.                                           | 2016      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 68^th^ Annual Conference of the European Federation of Animal Science, Tallinn, Estonia.                                                  | 2017      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 70^th^ Annual Conference of the European Federation of Animal Science, Ghent, Belgium.                                                    | 2019      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| ADSA Annual meeting, Cincinnati, Ohio                                                                                                     | 2019      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 9^th^ European Conference on Precision Livestock Farming Cork, Ireland.                                                                   | 2019      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| European Bovine Congress                                                                                                                  | 2019      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Annual ICAR meeting, Prague, Czech Republic.                                                                                              | 2019      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 9^th^ European Conference on Precision Livestock Farming Cork, Ireland                                                                    | 2019      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 39^th^ Discover Conference: The Transition Period -- From physiology to management, online meetings                                       | 2020      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Annual ICAR conference, Leeuwarden, The Netherlands                                                                                       | 2021      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Dairy InnovCongress, Namur, Belgium                                                                                                       | 2022      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Annual ICAR conference, Montreal, Canada                                                                                                  | 2022      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 10^th^ European Conference on Precision Livestock Farming, Vienna, Austria                                                                | 2022      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 43th Discover Conference: Dairy Cattle Reproduction -- Lessons learned and future frontiers                                               | 2022      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Joint Committee for Dairy Diagnostics, Rome, Italy                                                                                        | 2022      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| ### Informatics, Data science and statistical domain                                                                                      |           |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Post-graduate courses in applied informatics at Hogent                                                                                    | 2007-2010 |
|                                                                                                                                           |           |
| (<https://www.hogent.be/en/future-student/postgraduate-non-degrees/>).                                                                    |           |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| EPI on the Island 2009: An introduction to multilevel modeling, Prince Edward Island, Canada                                              | 2009      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Introduction to SAS, Institute for Continued Education, Ghent, Belgium                                                                    | 2009      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Introductory Statistics. Basics of Statistical Inference, Institute for Continued Education, Ghent, Belgium                               | 2009      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Analysis of Variance, Institute for Continued Education, Ghent, Belgium                                                                   | 2009      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Applied Linear Regression, Institute for Continued Education, Ghent, Belgium                                                              | 2010      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Applied Logistic Regression, Institute for Continued Education, Ghent, Belgium                                                            | 2011      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Multilevel Analysis for Grouped and Longitudinal Data, Institute for Continued Education, Ghent, Belgium                                  | 2011      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Design and Analysis of Clinical Trials, UGhent, Belgium                                                                                   | 2011      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Survival Analysis, UGhent, Belgium                                                                                                        | 2012      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Introduction to R, Institute for Continued Education, Ghent, Belgium                                                                      | 2013      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Tech Transfer Skills Workshop, Institute for Continued Education, Ghent, Belgium                                                          | 2013      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Multivariate data analysis, Institute for Continued Education, Ghent, Belgium                                                             | 2014      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| An Introduction to Big Data, Institute for Continued Education, Ghent, Belgium                                                            | 2015      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Professional Certificate in Bioinformatics, University College Dublin, Ireland                                                            | 2016      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Principles of Statistical Data Analysis, Ghent, Belgium                                                                                   | 2016      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Statistical Modelling, Ghent, Belgium                                                                                                     | 2016      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Data + AI summit. Brussels. Belgium.                                                                                                      | 2016      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Big Data Science, Ghent, Belgium                                                                                                          | 2017      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Computer-intensive Statistical Methods, Ghent, Belgium                                                                                    | 2017      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Databases, Ghent, Belgium                                                                                                                 | 2017      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Programming and Algorithms, Ghent, Belgium                                                                                                | 2017      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Statistical Computing, Ghent, Belgium                                                                                                     | 2017      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Data + AI summit. Dublin. Ireland.                                                                                                        | 2017      |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------+
