## Grants & Projects (Current, Pending, Finished)

### Current

| Project Description | Role | Year | Budget |
|:-----------------------------------------|:------:|:-----:|:--------:|
| DECIDE, Horizon Europe H2020-SFS-2018-2020 / 101000494, is a five-year Horizon 2020 project running from 2021 to 2025. It will develop data-driven decision support tools that offer robust and early signals of disease emergence and options for diagnostic confirmation. Moreover, options will be provided for controlling the disease along with their implications in terms of disease spread, economic burden and animal welfare. | CoPI | 2021 | €9,998,805 |
| PLAY BEHAVIOR CALVES IN EUROPE – A project funded by the Dutch dairy organization ZuivelNL to detect play behaviour in relation to space allowance using accelerometer and video analytics in dairy calves. | PI | 2023 | €100,000 |
| PLAY BEHAVIOR CALVES IN THE US – A project funded by the Cornell Institute for Digital Agriculture to detect play behaviour in relation to space allowance using accelerometer and video analytics in dairy calves. | PI | 2023 | €100,000 |
| GLOBAL GREENFEED PROJECT – A project funded by the Global Methane Hub to accurately measure and collect gas emissions from cattle with the GreenFeed system. | PI | 2024 | \$3,279,652 |
| AI-Driven Pandemic Preparedness in Dairy Farming: Enhancing Health Monitoring and Disease Management through Generative AI and Data Integration (Don Bennink Endowment). | PI | 2025 | \$249,175 |
| PDASP Track 3: Privacy-Preserving Dairy-Digitalization with Federal Learning (NSF-PDASP) | PI | 2025 | \$1,000,000 |
| Leveraging AI for Sustainable Livestock Farming: A RAG-Enhanced LLM Approach to Mitigate Carbon Emissions Around The World (Bezos Earth Fund) | PI | 2025 | \$50,000 |
| Selective Antimicrobial Disease Treatments in Dairy cows – Lessons learned from real-world farm data. (Federal Capacity Funds) | PI | 2025 | \$90,000 |
| A Multimodal Approach to Dairy Methane Reduction: Validation of Remote Satellite Images, Mid-InfraRed and Genomic Selection in Methane Mitigation (Cornell Atkinson Center for Sustainability) | PI | 2025 | \$150,000 |

### Pending

| Project Description | Role | Year | Budget |
|:-----------------------------------------|:-------:|:-----:|:--------:|
| HERD-AID:Connecting dairy herd health, environment and economics through applied and innovative decision modeling (FFAR) | Co-PI | 2025 | \$194,995 |
| DSFAS: A Farm-Deployable, Privacy-Aware Computer Vision Decision for Dairy Cattle Health and Welfare Management (USDA-NIFA-AFRI-011134) | PI | 2025 | \$650,000 |
| Modernizing Simulation Models to Enhance Computational Efficiency and User-Friendliness for Better Decision-Making on Small and Medium-Sized Dairy Farm (USDA-NIFA-AFRI-011134 | PI | 2025 | \$650,000 |
| Enhancing CNCPS Accuracy and Adaptability through Ontology-Enabled Farm Data Integration and AI-Driven Model Modernization (USDA-NIFA-AFRI-011134) | PI | 2025 | \$650,000 |

### Finished

| Project Description | Role | Year | Budget |
|:-----------------------------------------|:------:|:-----:|:--------:|
| GplusE was an FP7 project funded by the European Union. It was a five-year project from 2014 and 2018 executed by 15 research and industry partners. The project covered the interaction between genotype and environment contributing to the sustainability of dairy cow production systems. This was achieved through the optimal integration of genomic selection and novel management protocols based on the development and exploitation of genomic data and supporting novel phenotyping approaches. | CoPI | 2014 | €9,000,000 |
| In the SUMMERFAIR project (SUMmarizing transmission data to Enable data Reanalysis and predictions by FAIR data use) we tackle the issue of lack of a common terminology and need for repetition of costly experiments by developing a shared vocabulary (domain-ontology) and a workflow enabling reuse and combination of transmission data. The project running from 2021–2022 was granted by the dutch ZoNMW. | CoPI | 2021 | €250,000 |
| VEERKRACHT/Resilience – The transition period as a window and metabolic resilience to monitor of dairy cattle, granted by national Belgian VLAIO 2018 is a project that aims at creating tools to monitor the transition success of dairy cows at individual level and herd level. These tools allow the farmer to monitor individual animals at risk, in addition to allow individualized preventive measures. This will reduce the development of transition associated problems, which will increase productivity and animal welfare. | CoPI | 2018 | €1,300,000 |
| CLAWHEALTH.NL – A project sponsored by the Dutch Foundation WakkerDier to map the prevalence of leg and hoof problems in Dutch dairy cows, and to uncover the risk factors for leg and claw problems in the Netherlands using AI driven systematic reviews. | PI | 2023 | €100,000 |
