## Presentations

### Presentations available online

{{< video https://www.youtube.com/watch?v=mEnP4GJVhRM >}}

{{< video https://youtu.be/ibMIYSSPNwc?si=HYCIoTuj-OCwhyWo >}}

{{< video https://youtu.be/hh8AELptzH0?si=n7MAJlp_xPd9Ug2P >}}

### Invited speaker

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Title                                                                                                                                                                                          | Year      | Presentation                                                   |
+================================================================================================================================================================================================+:=========:+================================================================+
| Fresh Cow – Risiken und chancen. Was Sie darüber unbedingt wissen sollten! 2011. Presentation on Rinder-Gesundheitstag, Giesen, Germany.                                                       | 2011      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Visualisation of fertility records in dairy herds. 2012. Preconference seminar for SIVAR, Cremona, Italy.                                                                                      | 2012      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| The use of dairy data in herd health management. 2014. Northeast Dairy Production Medicine Symposium, New York, United States.                                                                 | 2014      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| The economics of breeding protocols in dairy cows. 2015. Consensus conference on breeding protocols. Nice, France.                                                                             | 2015      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Bovi-Analytics: an e-learning platform to educate veterinary students big data in dairy cows. 2015. Voorjaarsdagen. Amsterdam, The Netherlands.                                                | 2015      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Challenges for data-intensive projects. 2016. EU Commission workshop on animal genomics and breeding for sustainable production, Brussels, Belgium.                                            | 2016      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Big Dairy in Dairy Cows, 2016. ADSA Discovery Conference on Big Data in Dairy Cows, Chicago, United States.                                                                                    | 2016      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| From Big Data to Decisions in Dairy Cows, 2016. Spark Summit, Brussels, Belgium.                                                                                                               | 2016      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Visualisation and analysis of reproductive performance, 2017. Total Dairy Seminar, Keele, United Kingdom.                                                                                      | 2017      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Pitfalls in Dairy Analytics (advanced technical), 2017. Total Dairy Seminar, Keele, United Kingdom.                                                                                            | 2017      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Analysis of reproductive performance (farmer orientated), 2017. Total Dairy Seminar, Keele, United Kingdom.                                                                                    | 2017      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Transition management as a key to fertility success, 2017. Total Dairy Seminar, Keele, United Kingdom.                                                                                         | 2017      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| How to monitor productive performance on a small vs large dairy, 2017. Anembe congress, Pamplona, Spain.                                                                                       | 2017      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Common analytical data pitfalls every practitioner should know about, 2017. ANEMBE congress, Pamplona, Spain.                                                                                  | 2017      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Will semantics help disentangle the Gordian knot of Big Data in animal health, 2017. Semantics conference, Amsterdam, Belgium.                                                                 | 2017      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Monitoring fertility control programs in small and large dairy herds , 2017, The 7th National & 1st International Congress of Veterinary Gynecology, Marmaris, Turkey                          | 2017      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| A novel approach to data mining and prediction modelling in dairy cows, 2017. Big Data Conference, Vilnius, Lithuania.                                                                         | 2017      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| A Novel Approach to Data Mining And Prediction Modelling in Dairy Cows, 2018. Big Data Moscow, Russia.                                                                                         | 2018      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Transforming Big Data into Value: Put Data to Work for Your Dairy, 2018. Connect Summit, Beaver Creek, USA.                                                                                    | 2018      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Transforming Big Data into Value: Put Data to Work for Your Dairy (CDCB – 10 years of genomics)                                                                                                | 2018      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Metabolic clustering of dairy cows at early and peak lactation. Global Genetics Pathfinder Initiative, Rome, Italy, 2018.                                                                      | 2018      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Dairy Intelligence and Turning Data Into Information. 2019. Connect Summit, Beaver Creek, USA.                                                                                                 | 2019      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Predicting the Moment of Birth using Sensor Data in Dairy Cows. 2019. Big Data Conference, Vilnius, Lithuania.                                                                                 | 2019      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| What makes a biomarker a good one? 2019. Tartu, Estonia.                                                                                                                                       | 2019      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Put Data to Work for the Dairy Industry. 2020. National DHIA Leadership and Annual Meeting, Savannah, USA.                                                                                     | 2020      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Agricultural Genome to Phenome Initiative. AG2PI meeting 2020. Online meeting.                                                                                                                 | 2020      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Monitoring transition cows using novel techniques. ADSA 39th Discover meeting 2021. Online meeting.                                                                                            | 2021      |                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Using data to embrace excellence in hoof health – challenges and opportunities. 2022. 21st International symposium & 13th international conference on lameness in ruminants, Bloomington, USA. | 2022      | [Presentation](https://prezi.com/view/MRa09aTFjp0QhtfywUo2/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| How to Make Sense of 24x7 Sensor Data. 2022. Dairy Cattle Improvement Industry Forum, Lactanet, Toronto, Canada.                                                                               | 2022      | [Presentation](https://prezi.com/view/nLVoBNJdVJIOyIhyeOL3/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Sustainable dairy production, EU within a global perspective. VetCVE meeting 2023, Cork, Ireland.                                                                                              | 2023      | [Presentation](https://prezi.com/view/B3JPoKLALciOshVXXrRh/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| The Finnish Veterinary Congress, 2023, Helsinki, Finland.                                                                                                                                      | 2023      | [Presentation 1](https://prezi.com/view/ZqjPIpMl6FbaT4UDE7hE/) |
|                                                                                                                                                                                                |           |                                                                |
|                                                                                                                                                                                                |           | [Presentation 2](https://prezi.com/view/puBrsfmog5XBRI2fQyGC/) |
|                                                                                                                                                                                                |           |                                                                |
|                                                                                                                                                                                                |           | [Presentation 3](https://prezi.com/view/RVjxVRcjUdop0ulRPlNy/) |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| European Perspective on Longevity- the Data and Technology. Novus, 2024, Watkins Glen, USA.                                                                                                    | 2024      | [Presentation](https://prezi.com/view/TSLnUGj8Prs4nmhoqUME/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Advancing precision dairy farming through AI. Annual Meeting American Dairy Science Association, 2024.                                                                                         | 2024      | [Presentation](https://prezi.com/view/bFj1yT62ZGACMh6FnHLr/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Digital Dairy Farming, CIDA Symposium, 2024, Ithaca, USA.                                                                                                                                      | 2024      | [Presentation](https://prezi.com/view/z8wnDQHiyT8WQs63Erna/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Cattle Camp. 2024. Triesdorf, Germany.                                                                                                                                                         | 2024      | [Presentation 1](https://prezi.com/view/8UAHuRo7iv1E4CdMQ1hm/) |
|                                                                                                                                                                                                |           |                                                                |
|                                                                                                                                                                                                |           | [Presentation 2](https://prezi.com/view/w4L0dtz6sheWLCuTpmVr/) |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| How could AI change the dairy industry? Tri-State Dairy Nutrition Conference. 2024. Montpelier, USA.                                                                                           | 2024      | [Presentation](https://prezi.com/view/IOtYovVDtAGdggjkc2x6/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| CIDA Seminar, 2025, Ithaca, USA.                                                                                                                                                               | 2025      | [Presentation](https://prezi.com/view/z8wnDQHiyT8WQs63Erna/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| What can camera technology and artificial intelligence bring to a dairy in 2025? Operations Managers Conference, 2025, Syracuse, USA.                                                          | 2025      | [Presentation](https://prezi.com/view/9q7NlCyMisLRT8Xkmbw2/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| How artificial intelligence can transform an entire agricultural industry, or NOT? IEEE MeAVeAS. 2025. Pisa, Italy.                                                                            | 2025      | [Presentation](https://prezi.com/view/kd0XP8ubYMPYWvc1d6Cj/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Effectively Implementing AI at the Interface Between Veterinary and Dairy Science. Savy. 2025. Ithaca, USA.                                                                                    | 2025      | [Presentation](https://prezi.com/view/G0ybeFsLJbJpS93LGhlo/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Effectively Implementing AI at the Interface Between Veterinary and Dairy Science. VEE 2025. Brussels, Belgium                                                                                 | 2025      | [Presentation](https://prezi.com/view/FIEVxDgrACf0K6VwNPTz/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| How artificial intelligence can transform an entire agricultural industry, or NOT? AABP. 2025. Omaha, USA.                                                                                     | 2025      | [Presentation](https://prezi.com/view/TszKFVppAoueipQljo6O/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| How artificial intelligence can transform an entire agricultural industry, or NOT? 2026. Georgia Dairy Conference)                                                                             | 2026      | [Presentation](https://prezi.com/view/fzhVjeu6SevmvdmxAYHk/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Growing with AI — Input Optimization Webinar                                                                                                                                                   | 2026      | [Presentation](https://prezi.com/view/GigE4M1jXg5jfO3USDYC/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| The Use of Technologies for Precision Management- Exploring how sensor tech and automated systems are changing the game for genetic and health management. 2026. SIVAR-SIB. Cremona, Italy.    | 2026      | [Presentation 1](https://prezi.com/view/d9ia3HJX4AAFfQ3zcrea/) |
|                                                                                                                                                                                                |           |                                                                |
|                                                                                                                                                                                                |           | [Presentation 2](https://prezi.com/view/cxYfltepgO8pfwW5Nxv8/) |
|                                                                                                                                                                                                |           |                                                                |
|                                                                                                                                                                                                |           | [Presentation 3](https://prezi.com/view/xaw8kDEQ7bRBmDjJ7zuv/) |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Building the data-driven dairy: The Next Wave of AI, Interoperability, and Decision Support. 2026 (Online). Balchem Real Science Lecture.                                                      | 2026      | [Presentation](https://prezi.com/view/VoA7ZQ2Rq5RZXgw9cURO/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Using sensor technologies to quantify rumination: development of reference standards and validation for animal welfare and health recording. 2026. ICAR-IDF Conference. Verona, Italy.         | 2026      | [Presentation](https://prezi.com/view/Ujg8wf18nZSZ5lw16QDw/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+
| Van Data naar Daadkracht — Hoe vakmanschap, data en slimme sturing samen het verschil maken. 2026. De Graafstroom. Enspijk, The Netherlands.                                                   | 2026      | [Presentation](https://prezi.com/view/0IXigE1p9Nrbomu6rxqC/)   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------------------------------------------------+

### Extension workshops

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Title                                                                                                                                                                                                                                                                                                                         | Year    | Presentation                                                   |
+===============================================================================================================================================================================================================================================================================================================================+:=======:+================================================================+
| How we practitioners should implement our nutrition knowledge to help our farmers? 2011. Workshop on the 6th European Congress of Bovine Health Management, Liège, Belgium.                                                                                                                                                   | 2011    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Technology in dairy. 2012. Masterclasses for Zoetis, Cremona, Italy.                                                                                                                                                                                                                                                          | 2012    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| HACCP approaches for fertility management in livestock. 2013. Workshop on the 17th ESDAR Conference, Bologna, Italy.                                                                                                                                                                                                          | 2013    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Herd Health Management: The future for bovine practioners: challenge or opportunity. 2013. Masterclasses for Zoetis, Germany.                                                                                                                                                                                                 | 2013    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Visualisation of heat detection and conception rates in small and large dairy herds. 2013. Masterclasses for Zoetis, The Netherlands.                                                                                                                                                                                         | 2013    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Transition management and its influence on fertility. 2013. Presentation for Proveto, The Netherlands.                                                                                                                                                                                                                        | 2013    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Pitfalls in the analysis of reproductive records in dairy herds. 2013. Presentation for Proveto, The Netherlands.                                                                                                                                                                                                             | 2013    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Subclinical ketosis during the transition period. 2013. Launch Events Exxit Ketose, Elanco, Belgium.                                                                                                                                                                                                                          | 2013    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Masterclasses reproductive management in dairy cows. 2014. Zoetis, The Netherlands.                                                                                                                                                                                                                                           | 2014    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Visualisation and interpretation of reproductive herd records. 2014. International Cow Fertility Conference ‘New Science – New Practices’, Westport, Ireland.                                                                                                                                                                 | 2014    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Masterclasses reproductive management in dairy cows. 2015. Zoetis, Belgium.                                                                                                                                                                                                                                                   | 2015    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Masterclasses Transition Management. 2015. Zoetis, The Netherlands.                                                                                                                                                                                                                                                           | 2015    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Transforming Big Data into real world evidence for SARA. 2016. DairyCare Workshop on Sub-Acute Ruminal Acidosis, Glasgow, United Kingdom.                                                                                                                                                                                     | 2016    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Bovine herd health management. 2016. Workshop on the 20th ESDAR Conference, Lisbon, Portugal.                                                                                                                                                                                                                                 | 2016    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Dairy data management, where to start. 2017. Workshop on the ANEMBE Conference, Pamplona, Spain.                                                                                                                                                                                                                              | 2017    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| How to monitor reproductive performance, 2017. Workshop on ANEMBE Conference, Pamplona, Spain.                                                                                                                                                                                                                                | 2017    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Multiple sessions for the Ruminant Specialisation 2017-2018, Merelbeke, Belgium. (General introduction to dairy data analytics, common analytical data pitfalls every practitioner should know about, monitoring production, monitoring reproduction, insemination strategy, conception strategy, improve dairy cow fertility | 2017    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| The truth about transition disease in dairy cows, 2017. Dechra, Tielt, Belgium.                                                                                                                                                                                                                                               | 2017    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| First results of the GplusE project, 2017. Post-Education in Veterinary Medicine, Merelbeke, Belgium.                                                                                                                                                                                                                         | 2017    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Ruminant clinical cases, 2017. Institute for continued education at Ughent, Merelbeke, Belgium.                                                                                                                                                                                                                               | 2017    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Monitoring reproduction in high yielding dairy cows. Dyrlaeger & Ko, Vintermøde, 2018, Hovborg Kro, Denmark.                                                                                                                                                                                                                  | 2018    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Feeding the dairy cow – Basics of high yielding dairy cows. Vakdierenarts rund. 2018-2019, Merelbeke, Belgium.                                                                                                                                                                                                                | 2018    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Feeding the dairy cow –Feeding high intake and milk composition. Vakdierenarts rund. 2018-2019, Merelbeke, Belgium.                                                                                                                                                                                                           | 2018    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Zoetis Advanced Fertilitiy Consulting 2018-2019                                                                                                                                                                                                                                                                               | 2018    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Act, think and work like a datascientist. Bio-Informatics Course 2018, UCD Dublin, Ireland.                                                                                                                                                                                                                                   | 2018    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| GplusE Training School, 2018. Bucarest, Roumania/ Madrid, Spain.                                                                                                                                                                                                                                                              | 2018    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Big Data for Dairy and Monitoring Cow Health and Performance. Global Dairy Series Phibro Academy 2020. Online meeting.                                                                                                                                                                                                        | 2020    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| The veterinary toolbox for reproductive herd health management now and in the (near) future. Zoetis Poland 2020. Online meeting.                                                                                                                                                                                              | 2020    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| The importance of sensor data in transition cow monitoring. Alta Vet-to-vet webinar 2021. Online meeting.                                                                                                                                                                                                                     | 2021    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Detecting the subclinical diseased transition cow: how novel phenotyping strategies can help. Elanco Scientific Symposium 2021. Rotterdam. The Netherlands.                                                                                                                                                                   | 2021    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Not only a success story: A workshop on lessons learned from the past and what is really needed to move from precision to smart dairy farming! Workshop on the 10th ECPLF conference. Vienna, Austria.                                                                                                                        | 2022    |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Sustainable Ruminant Health. How to manage it successfully. 2023. Utrecht, The Netherlands.                                                                                                                                                                                                                                   | 2023    | [Presentation](https://prezi.com/view/mPsEJBmrGvacshFmgKkx/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Sustainable Ruminant Health. Presentation for DAP Oostland. 2023. Halle, The Netherlands.                                                                                                                                                                                                                                     | 2023    | [Presentation](https://prezi.com/view/QOyh0ollFwsmMxHjokJ5/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Sustainable dairy production from a global perspective. 2023. Boerensymposium, Groningen, The Netherlands.                                                                                                                                                                                                                    | 2023    | [Presentation](https://prezi.com/view/ZOLHC3p0xZsuagi4bjyF/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Meer melk uit (ruw)voer. Klantenavond 2023 Dierenkliniek Wolvega. Wolvega, The Netherlands.                                                                                                                                                                                                                                   | 2023    | [Presentation](https://prezi.com/view/0FNmDeFp8jgUfrzZ6iV9/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| NutriVice studie bijeenkomst 2023. Een toekomst voor de Nederlandse melkveehouderij. Ane & Velden, The Netherlands.                                                                                                                                                                                                           | 2023    | [Presentation](https://prezi.com/view/0FNmDeFp8jgUfrzZ6iV9/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Evolution or revolution. Future Food Utrecht Symposium. 2023. Driebergen, The Netherlands.                                                                                                                                                                                                                                    | 2023    | [Presentation](https://prezi.com/view/7pMuqV5fnZl7u46ci6Of/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Toekomst van de melkveehouderij in Nederland, Europa en daarbuiten. Dierenartsen Midden-Brabant (Online). 2024. The Netherlands                                                                                                                                                                                               | 2024    | [Presentation](https://prezi.com/view/1bcqp5GXaN9lzhFyoVLb/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Toekomst van de melkveehouderij in Nederland, Europa en daarbuiten. 2024. Boerensymposium. Utrecht, The Netherlands.                                                                                                                                                                                                          | 2024    | [Presentation](https://prezi.com/view/0hMkswYpDDG2ArA89jtT/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| How artificial intelligence can transform an entire agricultural industry, or NOT? 2025. Dairy Center of Excellence, Ithaca, USA.                                                                                                                                                                                             | 2025    | [Presentation](https://prezi.com/view/k7gYvnhrPkZUJqz4d7La/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| What can camera technology and artificial intelligence bring to a dairy in 2025? Operations Managers Conference. 2025. Syracuse, USA.                                                                                                                                                                                         |         |                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Eine Zukunft für die Milchwirtschaft. 2025. Hofheim, Germany.                                                                                                                                                                                                                                                                 | 2025    | [Presentation](https://prezi.com/view/P47z3gjBDPhV7Gvn9lTM/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Applications of artificial intelligence in the bovine practice. 2025. Bovine Practitioners Meeting. Hofheim, Germany.                                                                                                                                                                                                         | 2025    | [Presentation 1](https://prezi.com/view/JEGbdXfpraUQyyhj4d98/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 2](https://prezi.com/view/1JtWOiLccl4aZwITMEkk/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 3](https://prezi.com/view/of1D9pHC9rS7f4SjPXly/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 4](https://prezi.com/view/bibFyFyrUFkE3VC90KSw/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 5](https://prezi.com/view/RMueLhxCwovV2jQm2FQH/) |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Effectively Implementing AI at the Interface Between Veterinary and Dairy Science (Ohio Veterinarians Meeting)                                                                                                                                                                                                                | 2026    | [Presentation 1](https://prezi.com/view/JEGbdXfpraUQyyhj4d98/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 2](https://prezi.com/view/1JtWOiLccl4aZwITMEkk/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 3](https://prezi.com/view/of1D9pHC9rS7f4SjPXly/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 4](https://prezi.com/view/bibFyFyrUFkE3VC90KSw/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 5](https://prezi.com/view/RMueLhxCwovV2jQm2FQH/) |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| Toekomst van de melkveehouderij in Belgie, Europa en daarbuiten. Congres van de Brugse Dierenartsen Vereninging. 2025. Moerkerke, Belgium.                                                                                                                                                                                    | 2025    | [Presentation](https://prezi.com/view/nDpCHfZSFvSpU7pzRvtK/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| How artificial intelligence can transform an entire agricultural industry, or NOT? Smart Dairy Workshop Wisconsin. 2026. PDWP. Chippewa Falls & Manitowoc, USA.                                                                                                                                                               | 2026    | [Presentation](https://prezi.com/view/SeOUqQ9LyUkr3PFdUY1J/)   |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+
| The Use of Technologies for Precision Management- Exploring how sensor tech and automated systems are changing the game for genetic and health management. 2026. SIVAR-SIB. Cremona, Italy.                                                                                                                                   | 2026    | [Presentation 1](https://prezi.com/view/d9ia3HJX4AAFfQ3zcrea/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 2](https://prezi.com/view/cxYfltepgO8pfwW5Nxv8/) |
|                                                                                                                                                                                                                                                                                                                               |         |                                                                |
|                                                                                                                                                                                                                                                                                                                               |         | [Presentation 3](https://prezi.com/view/xaw8kDEQ7bRBmDjJ7zuv/) |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+----------------------------------------------------------------+

### Oral conference presentations

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| Title                                                                                                                                                                                                                                                                                                           | Year    | Presentation                                                 |
+=================================================================================================================================================================================================================================================================================================================+:=======:+==============================================================+
| The effect of marine algae supplementation in the ration of high yielding dairy cows during transition and its effect on metabolic parameters in the serum and follicular fluid around parturition. 2009. Oral presentation on the XI International Symposium on Ruminant Physiology, Clermont-Ferrand, France. | 2009    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| On-farm evaluation of the effect of metabolic diseases on the shape of the lactation curve in dairy cows through the milkbot lactation model. 2012. Oral presentation on the 27th World Buiatrics Congress, Lisbon, Portugal.                                                                                   | 2012    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| The past, the present and the future of bovine herd health management. 2015. 10th meeting of the European College of Bovine Herd Health Management, Maribor, Slovenia.                                                                                                                                          | 2015    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| Potential for novel glycan measurements in milk as biomarker phenotypes for dairy traits. 2016. Oral presentation on 67th Annual Conference of the European Federation of Animal Science, Belfast, United Kingdom.                                                                                              | 2016    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| Data Mining and Prediction Modelling in the Dairy Industry Using Time Series and Sliding Windows with Apache Spark 2. Data + AI summit 2016. Dublin. Ireland.                                                                                                                                                   | 2016    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| Exploratory classification of multiparous dairy cows based on fertility related phenotypes. 2017. Oral presentation on 68th Annual Conference of the European Federation of Animal Science, Tallinn, Estonia.                                                                                                   | 2017    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| Investigating metabolic phenotypes in multiparous dairy cows by component analysis and clustering. 2017. Oral presentation on 68th Annual Conference of the European Federation of Animal Science, Tallinn, Estonia.                                                                                            | 2017    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| The use of technologies in dairy innovation. 2018. European Regions Research and Innovation Conference – Food Safety 2020 - Seinäjoki, Finland.                                                                                                                                                                 | 2018    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| Can artificial intelligence be used on historical cow data to improve data quality and standardization of disease records. 2019. ICAR Annual meeting. Prague, Czech Republic.                                                                                                                                   | 2019    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| Predicting the next life event of cows by applying deep learning on sequential and pictorial data. 2019. 9th European Conference on Precision Livestock Farming Cork, Ireland.                                                                                                                                  | 2019    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| Modern tools for milk recording management. ICAR Annual meeting. Leeuwarden, the Netherlands. 2021. Online meeting.                                                                                                                                                                                             | 2021    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| Prediction of persistency at day 305 in lactation at the moment of the insemination decision. ICAR Conference 2023. Toledo. Spain.                                                                                                                                                                              | 2023    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| A predictive model for hypocalcemia in dairy cows utilizing behavioural sensor data combined with deep learning. ADSA Annual Meeting. 2023. Ottawa. Canada.                                                                                                                                                     | 2023    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| A Foundational Framework for Animal Behavior Analysis Using Computer Vision, AI4AS 2025. Zurich. Switzerland.                                                                                                                                                                                                   | 2025    | [Presentation](https://prezi.com/view/DQDjSybENZwwYGDND86L/) |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| ICAR IDF initiative on sensor data for functional traits: Genetics and reference standards for rumination. Precision Dairy Farming 2025. Christchurch. New Zealand.                                                                                                                                             | 2025    |                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
| A Foundational Framework for Animal Behavior Analysis Using Computer Vision. Precision Dairy Farming 2025. Christchurch. New Zealand.                                                                                                                                                                           | 2026    | [Presentation](https://prezi.com/view/hUL4WyzK04Q4saxgJbqI/) |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------------------------------------------------------------+
