## Publications

### (a1) Articles published in journals listed in the ISI Web of Science

| [Title]{.underline} | [Year]{.underline} | [IF]{.underline} |
|-----------------------------------------|---------------:|---------------:|
| Sitko, E. M., Hostens, M., O'Connor, J., Heffernan, C., McCarthy, J., & Butler, S. T. (2025). Predictors of reproductive outcomes in seasonal-calving, pasture-based lactating dairy cows. *Journal of Dairy Science*. https://doi.org/10.3168/jds.2025-27537 | 2025 | 3.7 |
| Hostens, M., Franceschini, S., van Leerdam, M., Yang, H., Pokharel, S., Liu, E., Sharma, S. (2025). The future of big data and artificial intelligence on dairy farms: A proposed dairy data ecosystem. *JDS Communications*. https://doi.org/10.3168/jdsc.2025-0843 | 2025 | 2.2 |
| Slegers, Y., Matthijs, M., Stegeman, A., Hostens, M., & de Wit, S. (2025). Applied research note: exploring the relationship between first-week mortality and performance after the first week in broiler chickens. *Journal of Applied Poultry Research*, 100611. https://doi.org/10.1016/j.japr.2025.100611 | 2025 | 2.0 |
| Brito, L. F., Heringstad, B., Klaas, I. C., Schodl, K., Cabrera, V. E., Stygar, A., Hostens, M., & Egger-Danner, C. (2025). Invited review: Using data from sensors and other precision farming technologies to enhance the sustainability of dairy cattle breeding programs. *Journal of Dairy Science*, 108(10), 10447–10474. https://doi.org/10.3168/jds.2025-26554 | 2025 | 3.7 |
| Liu, E., Yang, H., Sharma, S., van Leerdam, M. B., Niu, P., VandeHaar, M. J., & Hostens, M. (2025). Agents are all you need: Pioneering the use of agentic artificial intelligence to embrace large language models into dairy science. *Journal of Dairy Science*. https://doi.org/10.3168/jds.2025-26775 | 2025 | 3.7 |
| Kemel, C., Salamone, M., Aernouts, B., Adriaens, I., Opsomer, G., Hut, P., & Hostens, M. (2025). Association of artificial intelligence–predicted milk yield residuals to behavioral patterns and transition success in multiparous dairy cows. *Journal of Dairy Science*. https://doi.org/10.3168/jds.2024-26134 | 2025 | 3.7 |
| Wessels, W., Bokkers, E. A., de Boer, I. J., Meijer, E., Rodenburg, T. B., Hostens, M., & Koop, G. (2025). A systematic review and meta-analysis of lameness scoring methods and the prevalence of lameness of dairy cows in Northwest Europe. *Journal of Dairy Science*. https://doi.org/10.3168/jds.2025-26585 | 2025 | 3.7 |
| Slegers, Y., Hostens, M., de Wit, S., Stegeman, A., & Jensen, D. B. (2025). Predicting footpad lesion scores of Dutch broiler flocks using routinely collected data. *Smart Agricultural Technology*, 101080. https://doi.org/10.1016/j.atech.2025.101080 | 2025 | 5.7 |
| Van De Putte, T., Van Kerschaver, C., Hostens, M., & Degroote, J. (2025). Investigating the development of piglet feeding behaviour during the immediate postweaning phase using computer vision. *animal*, 19(6), 101524. https://doi.org/10.1016/j.animal.2025.101524 | 2025 | 4.2 |
| Pascottini, O. B., Crowe, A. D., Ramil, U. Y., Hostens, M., Opsomer, G., & Crowe, M. A. (2025). Perspectives in cattle reproduction for the next 20 years – A European context. *Theriogenology*, 233, 8–23. https://doi.org/10.1016/j.theriogenology.2024.11.007 | 2025 | 2.4 |
| Slegers, Y., Hostens, M., Matthijs, M. G. R., Stegeman, J. A., & de Wit, J. J. (2024). Broiler flocks in production systems with slower-growing breeds and reduced stocking density receive fewer antibiotic treatments and have lower mortality. *Poultry Science*, 103(11), 104197. https://doi.org/10.1016/j.psj.2024.104197 | 2024 | 3.8 |
| van Leerdam, M., Hut, P. R., Liseune, A., Slavco, E., Hulsen, J., & Hostens, M. (2024). A predictive model for hypocalcaemia in dairy cows utilizing behavioural sensor data combined with deep learning. *Computers and Electronics in Agriculture*, 220, 108877. https://doi.org/10.1016/j.compag.2024.108877 | 2024 | 7.7 |
| Chen, Y., Steeneveld, W., Frankena, K., Leemans, I., Aardema, H., Vos, P. L. A. M., Nielen, M., & Hostens, M. (2024). Association between days post-conception and lactation persistency in dairy cattle. *Journal of Dairy Science*, 107(8), 5794–5804. https://doi.org/10.3168/jds.2023-24282 | 2024 | 3.7 |
| Trapanese, L., Hostens, M., Salzano, A., & Pasquino, N. (2024). Short review of current limits and challenges of application of machine learning algorithms in the dairy sector. *Acta IMEKO*, 13(1), 1–7. https://doi.org/10.21014/actaimeko.v13i1.1725 | 2024 | 1.06 |
| Probo, M., Atashi, H., & Hostens, M. (2024). Lactation performances in primiparous Holstein cows following short and normal gestation lengths. *Frontiers in Veterinary Science*, 11, 1289116. https://doi.org/10.3389/fvets.2024.1289116 | 2024 | 2.6 |
| Salamone, M., Adriaens, I., Liseune, A., Heirbaut, S., Jing, X. P., Fievez, V., Vandaele, L., Opsomer, G., Hostens, M., & Aernouts, B. (2024). Milk yield residuals and their link with the metabolic status of dairy cows in the transition period. *Journal of Dairy Science*, 107(1), 317–330. https://doi.org/10.3168/jds.2023-23641 | 2024 | 3.7 |
| Hostens, M., Lam, T., & Koop, G. (2023). Sustainable Ruminant Health at Utrecht University. *American Journal of Veterinary Research*, 84(7), ajvr.23.05.0104. https://doi.org/10.2460/ajvr.23.05.0104 | 2023 | 1.3 |
| Zare, M., Atashi, H., & Hostens, M. (2022). Genome-Wide Association Study for Lactation Performance in the Early and Peak Stages of Lactation in Holstein Dairy Cows. *Animals*, 12(12), 1541. https://doi.org/10.3390/ani12121541 | 2022 | 2.7 |
| Chen, Y., Steeneveld, W., Nielen, M., & Hostens, M. (2023). Prediction of persistency for day 305 of lactation at the moment of the insemination decision. *Frontiers in Veterinary Science*, 10, 1264048. https://doi.org/10.3389/fvets.2023.1264048 | 2023 | 2.6 |
| Chen, Y., Atashi, H., Mota, R. R., Grelet, C., Vanderick, S., Hu, H., GplusE Consortium, & Gengler, N. (2023). Validating genomic prediction for nitrogen efficiency index and its composition traits of Holstein cows in early lactation. *Journal of Animal Breeding and Genetics*, 140(6), 695–706. https://doi.org/10.1111/jbg.12819 | 2023 | 1.9 |
| Franceschini, S., Grelet, C., Leblois, J., Gengler, N., Soyeurt, H., & GplusE consortium. (2022). Can unsupervised learning methods applied to milk recording big data provide new insights into dairy cow health? *Journal of Dairy Science*, 105(8), 6760–6772. https://doi.org/10.3168/jds.2022-21975 | 2022 | 3.7 |
| Chen, Y., Hostens, M., Nielen, M., Ehrlich, J., & Steeneveld, W. (2022). Herd level economic comparison between the shape of the lactation curve and 305 d milk production. *Frontiers in Veterinary Science*, 9, 997962. https://doi.org/10.3389/fvets.2022.997962 | 2022 | 2.6 |
| Hut, P. R., Kuiper, S. E. M., Nielen, M., Hulsen, J. H. J. L., Stassen, E. N., & Hostens, M. (2022). Sensor based time budgets in commercial Dutch dairy herds vary over lactation cycles and within 24 hours. *PLOS ONE*, 17(2), e0264392. https://doi.org/10.1371/journal.pone.0264392 | 2022 | 2.9 |
| Hut, P. R., Scheurwater, J., Nielen, M., van den Broek, J., & Hostens, M. (2022). Heat stress in a temperate climate leads to adapted sensor-based behavioral patterns of dairy cows. *Journal of Dairy Science*, 105(8), 6909–6922. https://doi.org/10.3168/jds.2021-21756 | 2022 | 3.7 |
| Kemel, C., Salamone, M., Van Loo, H., Latour, C., Vandeputte, S., Callens, J., Hostens, M., & Opsomer, G. (2022). Unaffected semen quality parameters in *Neospora caninum* seropositive Belgian Blue bulls. *Theriogenology*, 191, 10–15. https://doi.org/10.1016/j.theriogenology.2022.07.013 | 2022 | 2.4 |
| Salamone, M., Adriaens, I., Vervaet, A., Opsomer, G., Atashi, H., Fievez, V., Aernouts, B., & Hostens, M. (2022). Prediction of first test day milk yield using historical records in dairy cows. *Animal*, 16(11), 100658. https://doi.org/10.1016/j.animal.2022.100658 | 2022 | 4.0 |
| Zare, M., Atashi, H., & Hostens, M. (2022). Genome-Wide Association Study for Lactation Performance in the Early and Peak Stages of Lactation in Holstein Dairy Cows. *Animals*, 12(12), 1541. https://doi.org/10.3390/ani12121541 | 2022 | 2.7 |
| Atashi, H., Asaadi, A., & Hostens, M. (2021). Association between age at first calving and lactation performance, lactation curve, calving interval, calf birth weight, and dystocia in Holstein dairy cows. *PLOS ONE*, 16(1), e0244825. https://doi.org/10.1371/journal.pone.0244825 | 2021 | 2.9 |
| Atashi, H., Hostens, M., & GplusE consortium. (2021). Genetic parameters for milk urea and its relationship with milk yield and compositions in Holstein dairy cows. *PLOS ONE*, 16(6), e0253191. https://doi.org/10.1371/journal.pone.0253191 | 2021 | 2.9 |
| Atashi, H., & Hostens, M. (2021). Genetic Aspects of Somatic Cell Count in Holstein Dairy Cows in Iran. *Animals*, 11(6), 1637. https://doi.org/10.3390/ani11061637 | 2021 | 2.7 |
| Hut, P. R., Hostens, M., Beijaard, M. J., van Eerdenburg, F. J. C. M., Hulsen, J. H. J. L., Hooijer, G. A., Stassen, E. N., & Nielen, M. (2021). Associations between body condition score, locomotion score, and sensor-based time budgets of dairy cattle during the dry period and early lactation. *Journal of Dairy Science*, 104(4), 4746–4763. https://doi.org/10.3168/jds.2020-19200 | 2021 | 3.7 |
| Liseune, A., Van den Poel, D., Hut, P. R., van Eerdenburg, F. J., & Hostens, M. (2021). Leveraging sequential information from multivariate behavioral sensor data to predict the moment of calving in dairy cattle using deep learning. *Computers and Electronics in Agriculture*, 191, 106566. https://doi.org/10.1016/j.compag.2021.106566 | 2021 | 7.7 |
| Liseune, A., Salamone, M., Van den Poel, D., Van Ranst, B., & Hostens, M. (2021). Predicting the milk yield curve of dairy cows in the subsequent lactation period using deep learning. *Computers and Electronics in Agriculture*, 180, 105904. https://doi.org/10.1016/j.compag.2020.105904 | 2021 | 7.7 |
| Meyer, A., Faverjon, C., Hostens, M., Stegeman, A., & Cameron, A. (2021). Systematic review of the status of veterinary epidemiological research in two species regarding the FAIR guiding principles. *BMC Veterinary Research*, 17(1), 270. https://doi.org/10.1186/s12917-021-02971-1 | 2021 | 2.3 |
| Scheurwater, J., Hostens, M., Nielen, M., Heesterbeek, H., Schot, A., van Hoeij, R., & Aardema, H. (2021). Pressure measurement in the reticulum to detect different behaviors of healthy cows. *PLOS ONE*, 16(7), e0254410. https://doi.org/10.1371/journal.pone.0264392 | 2021 | 2.9 |
| Tobolski, D., Łukasik, K., Bacławska, A., Skarżyński, D. J., Hostens, M., & Barański, W. (2021). Prediction of Calving to Conception Interval Length Using Algorithmic Analysis of Endometrial mRNA Expression in Bovine. *Animals*, 11(1), 236. https://doi.org/10.3390/ani11010236 | 2021 | 2.7 |
| Wathes, D. C., Cheng, Z., Salavati, M., Buggiotti, L., Takeda, H., Tang, L., Becker, F., Ingvartsen, K. I., Ferris, C., Hostens, M., Crowe, M. A., & GplusE Consortium. (2021). Relationships between metabolic profiles and gene expression in liver and leukocytes of dairy cows in early lactation. *Journal of Dairy Science*, 104(3), 3596–3616. https://doi.org/10.3168/jds.2020-19165 | 2021 | 3.7 |
| Rousing, T., Holm, J. R., Krogh, M. A., Østergaard, S., & GplusE Consortium. (2020). Expert-based development of a generic HACCP-based risk management system to prevent critical negative energy balance in dairy herds. *Preventive Veterinary Medicine*, 175, 104849. https://doi.org/10.1016/j.prevetmed.2019.104849 | 2020 | 2.2 |
| Atashi, H., Salavati, M., De Koster, J., Crowe, M. A., Opsomer, G., GplusE consortium, & Hostens, M. (2020). Genome-wide association for metabolic clusters in early-lactation Holstein dairy cows. *Journal of Dairy Science*, 103(7), 6392–6406. https://doi.org/10.3168/jds.2019-17369 | 2020 | 3.7 |
| Atashi, H., Salavati, M., De Koster, J., Crowe, M. A., Opsomer, G., Hostens, M., & The GplusE Consortium. (2020). A Genome-Wide Association Study for Calving Interval in Holstein Dairy Cows Using Weighted Single-Step Genomic BLUP Approach. *Animals*, 10(3), 500. https://doi.org/10.3390/ani10030500 | 2020 | 2.7 |
| Atashi, H., Salavati, M., De Koster, J., Ehrlich, J., Crowe, M., Opsomer, G., GplusE consortium, & Hostens, M. (2020). Genome-wide association for milk production and lactation curve parameters in Holstein dairy cows. *Journal of Animal Breeding and Genetics*, 137(3), 292–304. https://doi.org/10.1111/jbg.12442 | 2020 | 1.9 |
| Atashi, H., Salavati, M., De Koster, J., Crowe, M. A., Opsomer, G., GplusE consortium, & Hostens, M. (2020). Genome-wide association for metabolic clusters in early-lactation Holstein dairy cows. *Journal of Dairy Science*, 103(7), 6392–6406. https://doi.org/10.3168/jds.2019-17369 | 2020 | 3.7 |
| Bogado Pascottini, O., Probo, M., LeBlanc, S. J., Opsomer, G., & Hostens, M. (2020). Assessment of associations between transition diseases and reproductive performance of dairy cows using survival analysis and decision tree algorithms. *Preventive Veterinary Medicine*, 176, 104908. https://doi.org/10.1016/j.prevetmed.2020.104908 | 2020 | 2.2 |
| Foldager, L., Gaillard, C., Sorensen, M. T., Larsen, T., Matthews, E., O'Flaherty, R., Carter, F., Crowe, M. A., Grelet, C., Salavati, M., Hostens, M., Ingvartsen, K. L., Krogh, M. A., & GplusE Consortium. (2020). Predicting physiological imbalance in Holstein dairy cows by three different sets of milk biomarkers. *Preventive Veterinary Medicine*, 179, 105006. https://doi.org/10.1016/j.prevetmed.2020.105006 | 2020 | 2.2 |
| Grelet, C., Froidmont, E., Foldager, L., Salavati, M., Hostens, M., Ferris, C. P., Ingvartsen, K. L., Crowe, M. A., Sorensen, M. T., Fernandez Pierna, J. A., Vanlierde, A., Gengler, N., GplusE Consortium, & Dehareng, F. (2020). Potential of milk mid-infrared spectra to predict nitrogen use efficiency of individual dairy cows in early lactation. *Journal of Dairy Science*, 103(5), 4435–4445. https://doi.org/10.3168/jds.2019-17910 | 2020 | 3.7 |
| Krogh, M. A., Hostens, M., Salavati, M., Grelet, C., Sorensen, M. T., Wathes, D. C., Ferris, C. P., Marchitelli, C., Signorelli, F., Napolitano, F., Becker, F., Larsen, T., Matthews, E., Carter, F., Vanlierde, A., Opsomer, G., Gengler, N., Dehareng, F., Crowe, M. A., Ingvartsen, K. L., … Foldager, L. (2020). Between- and within-herd variation in blood and milk biomarkers in Holstein cows in early lactation. *Animal*, 14(5), 1067–1075. https://doi.org/10.1017/S1751731119002659 | 2020 | 4.0 |
| Østergaard, S., Krogh, M. A., Oliveira, V. H. S., Larsen, T., GplusE Consortium, & Otten, N. D. (2020). Only few benefits from propylene glycol drench in early lactation for cows identified as physiologically imbalanced based on milk spectra analyses. *Journal of Dairy Science*, 103(2), 1831–1842. https://doi.org/10.3168/jds.2019-17205 | 2020 | 3.7 |
| Liseune, A., Salamone, M., Van den Poel, D., Van Ranst, B., & Hostens, M. (2020). Leveraging latent representations for milk yield prediction and interpolation using deep learning. *Computers and Electronics in Agriculture*, 175, 105600. https://doi.org/10.1016/j.compag.2020.105600 | 2020 | 7.7 |
| Llamas-Luceño, N., Hostens, M., Mullaart, E., Broekhuijse, M., Lonergan, P., & Van Soom, A. (2020). High temperature-humidity index compromises sperm quality and fertility of Holstein bulls in temperate climates. *Journal of Dairy Science*, 103(10), 9502–9514. https://doi.org/10.3168/jds.2019-18089 | 2020 | 3.7 |
| Bogado Pascottini, O., Probo, M., LeBlanc, S. J., Opsomer, G., & Hostens, M. (2020). Assessment of associations between transition diseases and reproductive performance of dairy cows using survival analysis and decision tree algorithms. *Preventive Veterinary Medicine*, 176, 104908. https://doi.org/10.1016/j.prevetmed.2020.104908 | 2020 | 2.2 |
| Asaadi, A., Kafi, M., Atashi, H., Azari, M., & Hostens, M. (2019). Frozen-thawed ampullary cell monolayer improves bovine embryo *in vitro* development and quality. *Zygote*, 27(5), 337–346. https://doi.org/10.1017/S0967199419000388 | 2019 | 1.5 |
| De Koster, J., Salavati, M., Grelet, C., Crowe, M. A., Matthews, E., O'Flaherty, R., Opsomer, G., Foldager, L., GplusE, & Hostens, M. (2019). Prediction of metabolic clusters in early-lactation dairy cows using models based on milk biomarkers. *Journal of Dairy Science*, 102(3), 2631–2644. https://doi.org/10.3168/jds.2018-15533 | 2019 | 3.7 |
| Grelet, C., Vanlierde, A., Hostens, M., Foldager, L., Salavati, M., Ingvartsen, K. L., Crowe, M., Sorensen, M. T., Froidmont, E., Ferris, C. P., Marchitelli, C., Becker, F., Larsen, T., Carter, F., GplusE Consortium, & Dehareng, F. (2019). Potential of milk mid-IR spectra to predict metabolic status of cows through blood components and an innovative clustering approach. *Animal*, 13(3), 649–658. https://doi.org/10.1017/S1751731118001751 | 2019 | 4.0 |
| Bogado Pascottini, O., Hostens, M., & Opsomer, G. (2018). Cytological endometritis diagnosed at artificial insemination in repeat breeder dairy cows. *Reproduction in Domestic Animals*, 53(2), 559–561. https://doi.org/10.1111/rda.13110 | 2018 | 1.6 |
| Crowe, M. A., Hostens, M., & Opsomer, G. (2018). Reproductive management in dairy cows – the future. *Irish Veterinary Journal*, 71, 1. https://doi.org/10.1186/s13620-017-0112-y | 2018 | 2.7 |
| Depreester, E., De Koster, J., Van Poucke, M., Hostens, M., Van den Broeck, W., Peelman, L., Contreras, G. A., & Opsomer, G. (2018). Influence of adipocyte size and adipose depot on the number of adipose tissue macrophages and the expression of adipokines in dairy cows at the end of pregnancy. *Journal of Dairy Science*, 101(7), 6542–6555. https://doi.org/10.3168/jds.2017-13777 | 2018 | 3.7 |
| Probo, M., Pascottini, O. B., LeBlanc, S., Opsomer, G., & Hostens, M. (2018). Association between metabolic diseases and the culling risk of high-yielding dairy cows in a transition management facility using survival and decision tree analysis. *Journal of Dairy Science*, 101(10), 9419–9429. https://doi.org/10.3168/jds.2018-14422 | 2018 | 3.7 |
| Bogado Pascottini, O., Hostens, M., Sys, P., Vercauteren, P., & Opsomer, G. (2017). Cytological endometritis at artificial insemination in dairy cows: Prevalence and effect on pregnancy outcome. *Journal of Dairy Science*, 100(1), 588–597. https://doi.org/10.3168/jds.2016-11529 | 2017 | 3.7 |
| De Koster, J., Urh, C., Hostens, M., Van den Broeck, W., Sauerwein, H., & Opsomer, G. (2017). Relationship between serum adiponectin concentration, body condition score, and peripheral tissue insulin response of dairy cows during the dry period. *Domestic Animal Endocrinology*, 59, 100–104. https://doi.org/10.1016/j.domaniend.2016.12.004 | 2017 | 1.9 |
| De Koster, J., Van Eetvelde, M., Hermans, K., Van den Broeck, W., Hostens, M., & Opsomer, G. (2017). Short communication: Limitations of glucose tolerance tests in the assessment of peripheral tissue insulin sensitivity during pregnancy and lactation in dairy heifers. *Journal of Dairy Science*, 100(3), 2381–2387. https://doi.org/10.3168/jds.2016-11792 | 2017 | 3.7 |
| Depreester, E., Meyer, E., Demeyere, K., Van Eetvelde, M., Hostens, M., & Opsomer, G. (2017). Flow cytometric assessment of myeloperoxidase in bovine blood neutrophils and monocytes. *Journal of Dairy Science*, 100(9), 7638–7647. https://doi.org/10.3168/jds.2016-12186 | 2017 | 3.7 |
| Hermans, K., Waegeman, W., Opsomer, G., Van Ranst, B., De Koster, J., Van Eetvelde, M., & Hostens, M. (2017). Novel approaches to assess the quality of fertility data stored in dairy herd management software. *Journal of Dairy Science*, 100(5), 4078–4089. https://doi.org/10.3168/jds.2016-11896 | 2017 | 3.7 |
| Pascottini, O. B., Hostens, M., Sys, P., Vercauteren, P., & Opsomer, G. (2017). Risk factors associated with cytological endometritis diagnosed at artificial insemination in dairy cows. *Theriogenology*, 92, 1–5. https://doi.org/10.1016/j.theriogenology.2017.01.004 | 2017 | 2.4 |
| Ververs, C., van Zijll Langhout, M., Hostens, M., Otto, M., Govaere, J., Durrant, B., & Van Soom, A. (2017). Reproductive performance parameters in a large population of game-ranched white rhinoceroses (*Ceratotherium simum simum*). *PLOS ONE*, 12(12), e0187751. https://doi.org/10.1371/journal.pone.0187751 | 2017 | 2.9 |
| Bogado Pascottini, O., Hostens, M., Dini, P., Vandepitte, J., Ducatelle, R., & Opsomer, G. (2016). Comparison between cytology and histopathology to evaluate subclinical endometritis in dairy cows. *Theriogenology*, 86(6), 1550–1556. https://doi.org/10.1016/j.theriogenology.2016.05.014 | 2016 | 2.4 |
| Bogado Pascottini, O., Hostens, M., Dini, P., Vandepitte, J., Ducatelle, R., & Opsomer, G. (2016). Distribution of inflammation and association between active and chronic alterations within the endometrium of dairy cows. *Reproduction in Domestic Animals*, 51(5), 751–757. https://doi.org/10.1111/rda.12742 | 2016 | 1.6 |
| De Koster, J., Hostens, M., Hermans, K., Van den Broeck, W., & Opsomer, G. (2016). Validation of different measures of insulin sensitivity of glucose metabolism in dairy cows using the hyperinsulinemic euglycemic clamp test as the gold standard. *Domestic Animal Endocrinology*, 57, 117–126. https://doi.org/10.1016/j.domaniend.2016.06.004 | 2016 | 1.9 |
| De Koster, J., Van den Broeck, W., Hulpio, L., Claeys, E., Van Eetvelde, M., Hermans, K., Hostens, M., Fievez, V., & Opsomer, G. (2016). Influence of adipocyte size and adipose depot on the in vitro lipolytic activity and insulin sensitivity of adipose tissue in dairy cows at the end of the dry period. *Journal of Dairy Science*, 99(3), 2319–2328. https://doi.org/10.3168/jds.2015-10440 | 2016 | 3.7 |
| Dini, P., Bogado Pascottini, O., Ducheyne, K., Hostens, M., & Daels, P. (2016). Holding equine oocytes in a commercial embryo-holding medium: New perspective on holding temperature and maturation time. *Theriogenology*, 86(5), 1361–1368. https://doi.org/10.1016/j.theriogenology.2016.04.079 | 2016 | 2.4 |
| Atanasov, B., Hostens, M., Hajrulai-Musliu, Z., Uzunov, R., Adamov, N., Davkov, F., Velev, R., Opsomer, G., & Dovenski, T. (2016). Comparison of PUFA Profiles in the Blood and in Follicular Fluid and its Association with Follicular Dynamics after PGF2α Induced Luteolysis in Dairy Cows. *Macedonian Veterinary Review*, 39(2), 175–183. https://doi.org/10.1515/macvetrev-2016-0083 | 2016 | 0.4 |
| Pascottini, O. B., Hostens, M., Dini, P., Van Eetvelde, M., Vercauteren, P., & Opsomer, G. (2016). Prevalence of cytological endometritis and effect on pregnancy outcomes at the time of insemination in nulliparous dairy heifers. *Journal of Dairy Science*, 99(11), 9051–9056. https://doi.org/10.3168/jds.2016-11348 | 2016 | 3.7 |
| Van Eetvelde, M., Kamal, M. M., Hostens, M., Vandaele, L., Fiems, L. O., & Opsomer, G. (2016). Evidence for placental compensation in cattle. *Animal*, 10(8), 1342–1350. https://doi.org/10.1017/S1751731116000318 | 2016 | 4.0 |
| De Koster, J., Hostens, M., Van Eetvelde, M., Hermans, K., Moerman, S., Bogaert, H., Depreester, E., Van den Broeck, W., & Opsomer, G. (2015). Insulin response of the glucose and fatty acid metabolism in dry dairy cows across a range of body condition scores. *Journal of Dairy Science*, 98(7), 4580–4592. https://doi.org/10.3168/jds.2015-9341 | 2015 | 3.7 |
| Dini, P., Farhoodi, M., Hostens, M., Van Eetvelde, M., Pascottini, O. B., Fazeli, M. H., & Opsomer, G. (2015). Effect of uterine lavage on neutrophil counts in postpartum dairy cows. *Animal Reproduction Science*, 158, 25–30. https://doi.org/10.1016/j.anireprosci.2015.04.005 | 2015 | 2.2 |
| Kamal, M. M., Van Eetvelde, M., Bogaert, H., Hostens, M., Vandaele, L., Shamsuddin, M., & Opsomer, G. (2015). Environmental factors and dam characteristics associated with insulin sensitivity and insulin secretion in newborn Holstein calves. *Animal*, 9(9), 1490–1499. https://doi.org/10.1017/S1751731115000701 | 2015 | 4.0 |
| Meganck, V., Goddeeris, B. M., De Campeneere, S., Hostens, M., Van Eetvelde, M., Piepers, S., Cox, E., & Opsomer, G. (2015). Effect of β-hydroxybutyric acid, parity, and body condition score on phenotype and proliferative capacity of colostral mononuclear leukocytes of high-yielding dairy cows. *Journal of Dairy Science*, 98(10), 6782–6791. https://doi.org/10.3168/jds.2014-8780 | 2015 | 3.7 |
| Pascottini, O. B., Dini, P., Hostens, M., Ducatelle, R., & Opsomer, G. (2015). A novel cytologic sampling technique to diagnose subclinical endometritis and comparison of staining methods for endometrial cytology samples in dairy cows. *Theriogenology*, 84(8), 1438–1446. https://doi.org/10.1016/j.theriogenology.2015.07.032 | 2015 | 2.4 |
| Atanasov, B., Hostens, M., Celeska, I., Ilieska, K., Opsomer, G., & Dovenski, T. (2015). Follicular dynamics following induced luteolysis and transvaginal ultrasound-guided aspiration of the largest follicle in dairy cows. *Vet arhiv*, 85(3), 247–260. | 2015 | 0.5 |
| Cools, S., Van den Broeck, W., Bossaert, P., Hostens, M., & Opsomer, G. (2014). A field study to unravel factors that are significantly associated with the secretory activity of the corpus luteum during the first three postpartum cycles in high yielding dairy cows. *Reproduction in Domestic Animals*, 49(6), 881–893. https://doi.org/10.1111/rda.12348 | 2014 | 1.6 |
| Cools, S., Van den Broeck, W., Vanhaecke, L., Heyerick, A., Bossaert, P., Hostens, M., & Opsomer, G. (2014). Feeding soybean meal increases the blood level of isoflavones and reduces the steroidogenic capacity in bovine corpora lutea. *Animal Reproduction Science*, 144(3–4), 79–89. https://doi.org/10.1016/j.anireprosci.2013.12.008 | 2014 | 2.2 |
| Kamal, M. M., Van Eetvelde, M., Depreester, E., Hostens, M., Vandaele, L., & Opsomer, G. (2014). Age at calving in heifers and level of milk production during gestation in cows are associated with the birth size of Holstein calves. *Journal of Dairy Science*, 97(9), 5448–5458. https://doi.org/10.3168/jds.2014-7898 | 2014 | 3.7 |
| Kamal, M. M., Van Eetvelde, M., Depreester, E., Hostens, M., Vandaele, L., & Opsomer, G. (2014). Age at calving in heifers and level of milk production during gestation in cows are associated with the birth size of Holstein calves. *Journal of Dairy Science*, 97(9), 5448–5458. https://doi.org/10.3168/jds.2014-7898 | 2014 | 3.7 |
| Verschave, S. H., Vercruysse, J., Forbes, A., Opsomer, G., Hostens, M., Duchateau, L., & Charlier, J. (2014). Non-invasive indicators associated with the milk yield response after anthelmintic treatment at calving in dairy cows. *BMC Veterinary Research*, 10, 264. https://doi.org/10.1186/s12917-014-0264-x | 2014 | 2.3 |
| Cools, S., Van den Broeck, W., De Vliegher, S., Piepers, S., Hostens, M., & Opsomer, G. (2013). Topographic distribution of the different cell types, connective tissue and vascular tissue/lumina within a functional bovine corpus luteum. *Reproduction in Domestic Animals*, 48(4), 627–635. https://doi.org/10.1111/rda.12136 | 2013 | 1.6 |
| Hostens, M., Fievez, V., Leroy, J. L., van de Burgwal, E. J., Van Ranst, B., Vlaeminck, B., & Opsomer, G. (2013). Milk fat saturation and reproductive performance in dairy cattle. *Animal Reproduction Science*, 141(3–4), 116–123. https://doi.org/10.1016/j.anireprosci.2013.08.001 | 2013 | 2.2 |
| Pardon, B., Hostens, M., Duchateau, L., Dewulf, J., De Bleecker, K., & Deprez, P. (2013). Impact of respiratory disease, diarrhea, otitis and arthritis on mortality and carcass traits in white veal calves. *BMC Veterinary Research*, 9, 79. https://doi.org/10.1186/1746-6148-9-79 | 2013 | 2.3 |
| Pardon, B., Hostens, M., Duchateau, L., Dewulf, J., De Bleecker, K., & Deprez, P. (2013). Impact of respiratory disease, diarrhea, otitis and arthritis on mortality and carcass traits in white veal calves. *BMC Veterinary Research*, 9, 79. https://doi.org/10.1186/1746-6148-9-79 | 2013 | 2.3 |
| Charlier, J., Hostens, M., Jacobs, J., Van Ranst, B., Duchateau, L., & Vercruysse, J. (2012). Integrating fasciolosis control in the dry cow management: the effect of closantel treatment on milk production. *PLOS ONE*, 7(8), e43216. https://doi.org/10.1371/journal.pone.0043216 | 2012 | 2.9 |
| Hostens, M., Ehrlich, J., Van Ranst, B., & Opsomer, G. (2012). On-farm evaluation of the effect of metabolic diseases on the shape of the lactation curve in dairy cows through the MilkBot lactation model. *Journal of Dairy Science*, 95(6), 2988–3007. https://doi.org/10.3168/jds.2011-4791 | 2012 | 3.7 |
| Hostens, M., Fievez, V., Leroy, J. L., Van Ranst, J., Vlaeminck, B., & Opsomer, G. (2012). The fatty acid profile of subcutaneous and abdominal fat in dairy cows with left displacement of the abomasum. *Journal of Dairy Science*, 95(7), 3756–3765. https://doi.org/10.3168/jds.2011-5092 | 2012 | 3.7 |
| Hostens, M., Fievez, V., Leroy, J. L., Van Ranst, J., Vlaeminck, B., & Opsomer, G. (2012). The fatty acid profile of subcutaneous and abdominal fat in dairy cows with left displacement of the abomasum. *Journal of Dairy Science*, 95(7), 3756–3765. https://doi.org/10.3168/jds.2011-5092 | 2012 | 3.7 |
| Pardon, B., Catry, B., Dewulf, J., Persoons, D., Hostens, M., De Bleecker, K., & Deprez, P. (2012). Prospective study on quantitative and qualitative antimicrobial and anti-inflammatory drug use in white veal calves. *Journal of Antimicrobial Chemotherapy*, 67(4), 1027–1038. https://doi.org/10.1093/jac/dkr570 | 2012 | 3.9 |
| Pardon, B., De Bleecker, K., Hostens, M., Callens, J., Dewulf, J., & Deprez, P. (2012). Longitudinal study on morbidity and mortality in white veal calves in Belgium. *BMC Veterinary Research*, 8, 26. https://doi.org/10.1186/1746-6148-8-26 | 2012 | 2.3 |
| van Knegsel, A. T., Hostens, M., de Vries Reilingh, G., Lammers, A., Kemp, B., Opsomer, G., & Parmentier, H. K. (2012). Natural antibodies related to metabolic and mammary health in dairy cows. *Preventive Veterinary Medicine*, 103(4), 287–297. https://doi.org/10.1016/j.prevetmed.2011.09.006 | 2012 | 2.2 |
| Wullepit, N., Hostens, M., Ginneberge, C., Fievez, V., Opsomer, G., Fremaut, D., & De Smet, S. (2012). Influence of a marine algae supplementation on the oxidative status of plasma in dairy cows during the periparturient period. *Preventive Veterinary Medicine*, 103(4), 298–303. https://doi.org/10.1016/j.prevetmed.2011.09.007 | 2012 | 2.2 |
| Hostens, M., Fievez, V., Vlaeminck, B., Buyse, J., Leroy, J., Piepers, S., De Vliegher, S., & Opsomer, G. (2011). The effect of marine algae in the ration of high-yielding dairy cows during transition on metabolic parameters in serum and follicular fluid around parturition. *Journal of Dairy Science*, 94(9), 4603–4615. https://doi.org/10.3168/jds.2010-3899 | 2011 | 3.7 |
| Pardon, B., Stuyven, E., Stuyvaert, S., Hostens, M., Dewulf, J., Goddeeris, B. M., Cox, E., & Deprez, P. (2011). Sera from dams of calves with bovine neonatal pancytopenia contain alloimmune antibodies directed against calf leukocytes. *Veterinary Immunology and Immunopathology*, 141(3–4), 293–300. https://doi.org/10.1016/j.vetimm.2011.02.017 | 2011 | 1.4 |
| Hostens, M., Bossaert, P., Cools, S., de Kruif, A., & Opsomer, G. (2010). Het gebruik van glucogene precursoren in de voeding van hoogproductief melkvee. *Vlaams Diergeneeskundig Tijdschrift*, 79(4), 247–258. | 2010 | 0.2 |
| Ververs, C., Hostens, M., Caluwaerts, T., de Kruif, A., & Opsomer, G. (2010). Is er een verband tussen het verloop van de aanvangsfase van de lactatiecurve en het optreden van de eerste oestrus post partum bij hoogproductieve melkkoeien? *Vlaams Diergeneeskundig Tijdschrift*, 79(4), 381–388. | 2010 | 0.2 |

### (a2) Articles published in scholarly or scientific journals with a wide distribution, international peer review

| Title | Year |
|--------------------------------------------------------|---------------:|
| van Schaik, G., Hostens, M., Faverjon, C., Jensen, D. B., Kristensen, A. R., Ezanno, P., Frössling, J., Dórea, F., Jensen, B. B., Carmo, L. P., Steeneveld, W., Rushton, J., Gilbert, W., Bearth, A., Siegrist, M., Kaler, J., Ripperger, J., Siehler, J., de Wit, S., Garcia-Morante, B., … Nielen, M. (2023). *The DECIDE project: from surveillance data to decision-support for farmers and veterinarians*. Open Research Europe, 3, 82. https://doi.org/10.12688/openreseurope.15988.1 | 2023 |
| Wathes, D. C., Becker, F., Buggiotti, L., Crowe, M. A., Ferris, C., Foldager, L., … GplusE Consortium. (2021). *Associations between circulating IGF-1 concentrations, disease status and the leukocyte transcriptome in early lactation dairy cows*. Ruminants, 1(2), 147–177. | 2021 |
| Hermans, K., Opsomer, G., Waegeman, W., Moerman, S., De Koster, J., Van Eetvelde, M., Van Ranst, B., Hostens, M. (2018). *Interpretation and visualisation of data from dairy herds*. In Practice, 40(5), 195–203. | 2018 |
| Dehkordi, S. K., Vlaeminck, B., Hostens, M., Opsomer, G., & Fievez, V. (2008). *In vitro rumen biohydrogenation of trans‑10, cis‑12 conjugated linoleic acid in a lipid‑encapsulated (LE‑CLA) supplement incorporated or not in a processing pellet*. Communications in Agricultural and Applied Biological Sciences, 73(1), 119–122. | 2008 |

### (b2) Chapters in books

| Title | Year |
|-----------------------------------------------------------|------------:|
| Noor, S., Bokma, J., Pardon, B., van Schaik, G., & Hostens, M. (2024). *Agri Semantics: developments to improve data interoperability to support farm information management and decision support systems in agriculture*. In **Smart farms: Improving data‑driven decision making in agriculture** (pp. 75–96). Burleigh Dodds Science Publishing Limited. | 2024 |
| Hermans, K., Van Ranst, B., Opsomer, G., & Hostens, M. (2018). *Promises and challenges of big data associated with automated dairy cow welfare assessment*. In A. Butterworth (Ed.), **Animal Welfare in a Changing World** (pp. 199–207). CAB International. | 2018 |

### (p1) Articles in proceedings listed in the ISI Web of Science

| Title | Year |
|-----------------------------------------------------------|-------:|
| Noor, S., Degroote, J., Van Schaik, G., Pardon, B., Bokma, J., Slegers, Y., Morante, B., & Hostens, M. (2024). *Advancing precision livestock farming through ontology-driven interoperable health data management: Extending the Livestock Health Ontology (LHO) for enhanced disease surveillance*. In **11th European Conference on Precision Livestock Farming**, Bologna, Italy. | 2024 |
| Egger-Danner, C., Klaas, I., Brito, L., Schodl, K., Bewley, J. M., Cabrera, V., Haskell, M. J., Iwersen, M., Heringstad, B., Stock, K., Stygar, A., van der Linde, R., Hostens, M., Charfeddine, N., Gengler, N., & Vasseur, E. (2024). *Improving animal health and welfare by using sensor data in herd management and dairy cattle breeding – a joint initiative of ICAR and IDF*. In **11th European Conference on Precision Livestock Farming**, Bologna, Italy. | 2024 |
| Kemel, C., Salamone, M., Hut, P., Adriaens, I., Aernouts, B., & Hostens, M. (2024). *Association between AI‑generated milk yield residuals as measure of transition success and behavioural patterns in dairy cows*. In **11th European Conference on Precision Livestock Farming**, Bologna, Italy. | 2024 |
| Bokma, J., Santman‑Berends, I., Vidal, G., Hostens, M., Ribbens, S., Evrard, J., Theuns, S., Sánchez‑Miguel, C., van Schaik, G., & Pardon, B. (2023). *European veterinary barometer for bovine respiratory diseases: a comprehensive tool for mapping diagnostic test results and geolocation for respiratory tract samples from cattle*. In **Proc. 5th International Conference of the European College of Veterinary Microbiology**. | 2023 |
| Bokma, J., Santman‑Berends, I., Vidal, G., Hostens, M., Ribbens, S., Evrard, J., Theuns, S., van Schaik, G., & Pardon, B. (2023). *European Veterinary Barometer for Bovine Respiratory Diseases: a tool showing diagnostic test results and geolocation of respiratory tract samples from cattle*. In **Proc. European Buiatrics Congress and ECBHM Jubilee Symposium**. | 2023 |
| Slavco, E., De Vos, M., Hostens, M., Top, J., & Fischer, E. A. J. (2022). *Infection Transmission Ontology: Standardization of Infection Transmission Data*. In **IEEE International Conference on e‑Science**, pp. 65–73. https://doi.org/10.1109/eScience55777.2022.00021 | 2022 |
| Chen, Y., Hostens, M., Nielen, M., Ehrlich, J., & Steeneveld, W. (2022). *An empirical analysis of economic herd performance in relation to herd lactation curve characteristics*. In **European Conference on Precision Livestock Farming & International Conference on Precision Dairy Farming**, Vienna, Austria, pp. 728–736. | 2022 |
| Chen, Y., Hostens, M., Nielen, M., Ehrlich, J., & Steeneveld, W. (2022). *An empirical analysis of economic herd performance in relation to herd lactation curve characteristics*. In **Dair’Innov Congress**, Namur, Belgium, p. 35. | 2022 |
| Chen, Y., Hostens, M., Nielen, M., Ehrlich, J., & Steeneveld, W. (2021). *An empirical analysis on the association between persistency of dairy cows and economic herd performance*. In **ISESSAH**, p. 72. | 2021 |
| Salamone, M., Adriaens, I., Hostens, M., & Aernouts, B. (2021). *The Individual Transition Index: development of a new window inside the transition period*. Presented at **Precision Livestock Farming Workshop Seminar**, Leuven, Belgium (virtual). | 2021 |
| Salamone, M., Adriaens, I., Opsomer, G., Aernouts, B., & Hostens, M. (2021). *Machine‑learning‑based prediction of test day milk yield using historical data of the previous lactation*. Presented at **44th ICAR Annual Conference** (virtual). | 2021 |
| Lietaer, L., Hernandez Sanabria, E., Hostens, M., Vlaeminck, L., Van Soom, A., Van de Wiele, T., & Opsomer, G. (2019). Presented at **23rd Annual Conference of the European Society for Domestic Animal Reproduction (ESDAR)**. | 2019 |
| Salamone, M., Atashi, H., Salavati, M., De Koster, J., Crowe, M. A., Opsomer, G., & Hostens, M. (2019). *Genome‑wide association for metabolic adaptation in early lactation dairy cows*. Presented at **70th Annual Meeting of EAAP**, Ghent, Belgium. | 2019 |
| Salamone, M., Atashi, H., De Koster, J., Opsomer, G., & Hostens, M. (2019). *Genetic parameters for lactation curve traits in Holstein dairy cows*. Presented at **70th Annual Meeting of EAAP**, Ghent, Belgium. | 2019 |
| De Koster, J., Opsomer, G., & Hostens, M. (2018). *Metabolic clustering of dairy cows at early and peak lactation*. Presented at **22nd Annual Conference of ESDAR**. | 2018 |
| Gengler, N., & Hostens, M. (2018). *How fast can we change resilience and efficiency through breeding and management?* In **Book of Abstracts, 69th EAAP Annual Meeting**, p. 264. | 2018 |
| Grelet, C., Froidmont, E., Hostens, M., Vanlierde, A., Foldager, L., Salavati, M., Ingvartsen, K., Sorensen, M., Crowe, M., Ferris, C., & Marchitelli, C. (2018). *Predicting nitrogen efficiency of dairy cows through milk FT‑MIR spectra*. In **Book of Abstracts, 69th EAAP Annual Meeting**. | 2018 |
| Dini, P., Pascottini, O. B., Hostens, M., & Daels, P. (2016). *Holding equine oocytes in Syngro® embryo holding medium at 4 °C*. **International Symposium on Equine Embryo Transfer and Technology**, Ghent, Belgium. | 2016 |
