## Teaching

### Professionalization of education

-   **University Teaching Qualification** at Centre for Academic Teaching and Learning, Utrecht, The Netherlands, 2021

### Teaching experience

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *Institution*                                                                                                                                                                                    | *Duration*    | *Subject / course title*                                                                                                                                                                                                   |
+==================================================================================================================================================================================================+===============+============================================================================================================================================================================================================================+
| [**Cornell University**]{.underline}                                                                                                                                                             |               |                                                                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Undergraduate in Animal Science                                                                                                                                                                  | 2024-present  | Main lecturer in *‘Data Science Applications in Agriculture’*                                                                                                                                                              |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2024-present  | Co-lecturer in Hackathon in Digital Agriculture                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  |               | Main lecturer in *‘Digital Dairy Management and Data Analytics’*                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**Utrecht University**]{.underline}                                                                                                                                                             |               |                                                                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Master of Veterinary Medicine (<https://www.uu.nl/masters/diergeneeskunde>)                                                                                                                      | 2019-present  | Main developer and co-lecturer of the ‘*Dairy Health Management’* course.                                                                                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2022-2023     | Main developer and lecturer of the ‘*Dier and Data’* course.                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2019-present  | Main lecturer in *‘International Dairy Study Trip’*                                                                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2019-2024     | Clinical rotations in *‘Bovine health management’*                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2019-2023     | Main lecturer in ‘*Veal calf management’*                                                                                                                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Bachelor of Clinical Sciences                                                                                                                                                                    | 2022-2023     | Co-developer of ‘*Digitalization and technology in clinical sciences’*.                                                                                                                                                    |
|                                                                                                                                                                                                  |               |                                                                                                                                                                                                                            |
| (<https://www.uu.nl/bachelors/zorg-gezondheid-en-samenleving>)                                                                                                                                   |               |                                                                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Bachelor of Veterinary Medicine (<https://www.uu.nl/bachelors/diergeneeskunde>).                                                                                                                 | 2019-2023     | Weekly lectures in the Bachelor of Veterinary Medicine on bovine health management.                                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Master of Bio-informatics and bio-complexity (<https://www.uu.nl/en/masters/bioinformatics-and-biocomplexity/study-programme>)                                                                   | 2019-2023     | Co-lecturer *‘Introductory course to bioinformatics’*                                                                                                                                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lifelong learning course                                                                                                                                                                         | 2022-2023     | Development and main lecturer for the post-graduate course                                                                                                                                                                 |
|                                                                                                                                                                                                  |               |                                                                                                                                                                                                                            |
|                                                                                                                                                                                                  |               | *‘Sustainable Ruminant Health’*                                                                                                                                                                                            |
|                                                                                                                                                                                                  |               |                                                                                                                                                                                                                            |
|                                                                                                                                                                                                  |               | (<https://www.uu.nl/professionals/programmas/sustainable-ruminant-health>)                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Inter-faculty course                                                                                                                                                                             | 2021-2023     | Co-development and main lecturer for ‘*Dutch Dairy Student Innovation Challenge*’  (<https://ewuu.nl/en/education/challenges/dutch-dairy-challenge/>)                                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**Ghent University**]{.underline}                                                                                                                                                               |               |                                                                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Bachelor of Science in Bioscience Engineering Technology                                                                                                                                         | 2020- present | Co-lecturer in ‘*Animal Physiology*‘ (<https://studiekiezer.ugent.be/studiefiche/en/I700213/2023> )                                                                                                                        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2020- present | Co-lecturer in ‘*Reproductive Physiology of Animals’*                                                                                                                                                                      |
|                                                                                                                                                                                                  |               |                                                                                                                                                                                                                            |
|                                                                                                                                                                                                  |               | (<https://studiekiezer.ugent.be/studiefiche/en/I700042/2023> )                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Master of Science in Bioscience Engineering Technology: Agriculture and Horticulture (Plant and Animal Production)                                                                               | 2020- present | Main lecturerin *‘Animal Production Systems*’ (<https://studiekiezer.ugent.be/studiefiche/en/I700259/2023>)                                                                                                                |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Bachelor of Science in Veterinary Medicine –                                                                                                                                                     | 2020-present  | Co-lecturer in ‘*Physiology and Pathophysiology I’* (<https://studiekiezer.ugent.be/studiefiche/en/G000720/2022>) and ‘*Physiology and Pathophysiology II‘* (<https://studiekiezer.ugent.be/studiefiche/en/G000862/2022>). |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Master of Science in Veterinary Medicine – Main subject: Ruminants – Cluster Food Producing Animals – Courses in Ruminant and Porcine Herd Health Medicine, with Clinical Training I, II and III | 2015-2018     | Theoretical courses for Courses in *Ruminant and Porcine Herd Health Medicine, with Clinical Training II and III.*                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2014-2018     | Weekly practical training sessions on herd record interpretation for Courses in *Ruminant and Porcine Herd Health Medicine, with Clinical Training III*.                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2007-2018     | Clinical training III during nightly duties at the Veterinary Service of the Department of Reproduction, Obstetrics and Herd Health.                                                                                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2008-2018     | Clinical training III during *Bovine Herd Health* service visits.                                                                                                                                                          |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Institute for Continued Education at Faculty of Veterinary Medicine                                                                                                                              | 2010          | *A practical approach to risk factors for transition cows.*                                                                                                                                                                |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2012          | *Ration balancing for dairy cows, more than VEM and DVE.*                                                                                                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2013          | *Key Performance Indicators on dairy herds.*                                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2013          | *To synch or not to synch dairy cows.*                                                                                                                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2014          | *Factors influencing reproduction and production results in dairy cows.*                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2015          | *Data management in high yielding dairy cows.*                                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2016          | *Transition cows disease.*                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2018          | *Short course Dairy Cow Nutrition*                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                  | 2019          | *Short course Dairy Cow Nutrition*                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Basic Summer Course on Veterinary Epidemiology                                                                                                                                                   | 2016          | *Big Data in Dairy Analytics*                                                                                                                                                                                              |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**University College Dublin**]{.underline}                                                                                                                                                      |               |                                                                                                                                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Summer school – Professional Certificate in Bioinformatics                                                                                                                                       | 2017          | *An introduction to scalable data analytics in animal science*                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
