name: Quarto Website CI/CD

on:
  push:
    branches: [ main ]  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.4.550'

      - name: Install R and Packages
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          build-essential \
          r-base-dev

      - name: Restore R environment
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - name: Publish Site to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          quarto publish gh-pages --no-browser --no-prompt
